language:
    - c
    - cpp

sudo: required
dist: xenial

env:
  global:
    - PROTOBUF_VERSION=3.7.1
    - PROTOBUF_C_VERSION=1.3.2
    - PKG_CONFIG_PATH=$HOME/protobuf-$PROTOBUF_VERSION-bin/lib/pkgconfig:$HOME/protobuf-c-$PROTOBUF_C_VERSION-bin/lib/pkgconfig
    - C_INCLUDE_PATH=$HOME/protobuf-c-$PROTOBUF_C_VERSION-bin/include

install:
    - wget https://github.com/protocolbuffers/protobuf/archive/v$PROTOBUF_VERSION.tar.gz
    - tar xf v$PROTOBUF_VERSION.tar.gz
    - ( cd protobuf-$PROTOBUF_VERSION && ./autogen.sh && ./configure --prefix=$HOME/protobuf-$PROTOBUF_VERSION-bin && make -j2 && make install )
    - wget https://github.com/protobuf-c/protobuf-c/archive/v$PROTOBUF_C_VERSION.tar.gz
    - tar xf v$PROTOBUF_C_VERSION.tar.gz
    - ( cd protobuf-c-$PROTOBUF_C_VERSION && ./autogen.sh && ./configure --prefix=$HOME/protobuf-c-$PROTOBUF_C_VERSION-bin && make -j2 && make install )

script:
    - ./autogen.sh
    - ./configure
    - make
