/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol.proto */

#ifndef PROTOBUF_C_protocol_2eproto__INCLUDED
#define PROTOBUF_C_protocol_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Field Field;
typedef struct _Document Document;
typedef struct _RequestDocumentAdd RequestDocumentAdd;
typedef struct _RequestDocumentRemove RequestDocumentRemove;
typedef struct _RequestLookup RequestLookup;
typedef struct _ResponseOperate ResponseOperate;
typedef struct _ResponseLookup ResponseLookup;


/* --- enums --- */

/*
 **
 * basic
 */
typedef enum _ErrorCode {
  ERROR_CODE__ERROR_CODE_SUCCESS = 0,
  ERROR_CODE__ERROR_CODE_INVALID_ARGUMENT = -1,
  ERROR_CODE__ERROR_CODE_QUEUE_FULL = -2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ERROR_CODE)
} ErrorCode;

/* --- messages --- */

struct  _Field
{
  ProtobufCMessage base;
  uint32_t type;
  char *term;
  char *valuestr;
  int32_t valueint32;
  protobuf_c_boolean indexable;
};
#define FIELD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&field__descriptor) \
    , 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0 }


struct  _Document
{
  ProtobufCMessage base;
  uint64_t pk;
  size_t n_fields;
  Field **fields;
};
#define DOCUMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&document__descriptor) \
    , 0, 0,NULL }


/*
 **
 * request
 */
struct  _RequestDocumentAdd
{
  ProtobufCMessage base;
  size_t n_documents;
  Document **documents;
};
#define REQUEST_DOCUMENT_ADD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&request_document_add__descriptor) \
    , 0,NULL }


struct  _RequestDocumentRemove
{
  ProtobufCMessage base;
  size_t n_pks;
  uint64_t *pks;
};
#define REQUEST_DOCUMENT_REMOVE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&request_document_remove__descriptor) \
    , 0,NULL }


struct  _RequestLookup
{
  ProtobufCMessage base;
  size_t n_terms;
  char **terms;
  uint32_t limit;
};
#define REQUEST_LOOKUP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&request_lookup__descriptor) \
    , 0,NULL, 0 }


/*
 **
 * response
 */
struct  _ResponseOperate
{
  ProtobufCMessage base;
  ErrorCode code;
  char *msg;
};
#define RESPONSE_OPERATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&response_operate__descriptor) \
    , ERROR_CODE__ERROR_CODE_SUCCESS, (char *)protobuf_c_empty_string }


struct  _ResponseLookup
{
  ProtobufCMessage base;
  size_t n_documents;
  Document **documents;
  ErrorCode code;
  char *msg;
  uint32_t total;
};
#define RESPONSE_LOOKUP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&response_lookup__descriptor) \
    , 0,NULL, ERROR_CODE__ERROR_CODE_SUCCESS, (char *)protobuf_c_empty_string, 0 }


/* Field methods */
void   field__init
                     (Field         *message);
size_t field__get_packed_size
                     (const Field   *message);
size_t field__pack
                     (const Field   *message,
                      uint8_t             *out);
size_t field__pack_to_buffer
                     (const Field   *message,
                      ProtobufCBuffer     *buffer);
Field *
       field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   field__free_unpacked
                     (Field *message,
                      ProtobufCAllocator *allocator);
/* Document methods */
void   document__init
                     (Document         *message);
size_t document__get_packed_size
                     (const Document   *message);
size_t document__pack
                     (const Document   *message,
                      uint8_t             *out);
size_t document__pack_to_buffer
                     (const Document   *message,
                      ProtobufCBuffer     *buffer);
Document *
       document__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   document__free_unpacked
                     (Document *message,
                      ProtobufCAllocator *allocator);
/* RequestDocumentAdd methods */
void   request_document_add__init
                     (RequestDocumentAdd         *message);
size_t request_document_add__get_packed_size
                     (const RequestDocumentAdd   *message);
size_t request_document_add__pack
                     (const RequestDocumentAdd   *message,
                      uint8_t             *out);
size_t request_document_add__pack_to_buffer
                     (const RequestDocumentAdd   *message,
                      ProtobufCBuffer     *buffer);
RequestDocumentAdd *
       request_document_add__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   request_document_add__free_unpacked
                     (RequestDocumentAdd *message,
                      ProtobufCAllocator *allocator);
/* RequestDocumentRemove methods */
void   request_document_remove__init
                     (RequestDocumentRemove         *message);
size_t request_document_remove__get_packed_size
                     (const RequestDocumentRemove   *message);
size_t request_document_remove__pack
                     (const RequestDocumentRemove   *message,
                      uint8_t             *out);
size_t request_document_remove__pack_to_buffer
                     (const RequestDocumentRemove   *message,
                      ProtobufCBuffer     *buffer);
RequestDocumentRemove *
       request_document_remove__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   request_document_remove__free_unpacked
                     (RequestDocumentRemove *message,
                      ProtobufCAllocator *allocator);
/* RequestLookup methods */
void   request_lookup__init
                     (RequestLookup         *message);
size_t request_lookup__get_packed_size
                     (const RequestLookup   *message);
size_t request_lookup__pack
                     (const RequestLookup   *message,
                      uint8_t             *out);
size_t request_lookup__pack_to_buffer
                     (const RequestLookup   *message,
                      ProtobufCBuffer     *buffer);
RequestLookup *
       request_lookup__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   request_lookup__free_unpacked
                     (RequestLookup *message,
                      ProtobufCAllocator *allocator);
/* ResponseOperate methods */
void   response_operate__init
                     (ResponseOperate         *message);
size_t response_operate__get_packed_size
                     (const ResponseOperate   *message);
size_t response_operate__pack
                     (const ResponseOperate   *message,
                      uint8_t             *out);
size_t response_operate__pack_to_buffer
                     (const ResponseOperate   *message,
                      ProtobufCBuffer     *buffer);
ResponseOperate *
       response_operate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   response_operate__free_unpacked
                     (ResponseOperate *message,
                      ProtobufCAllocator *allocator);
/* ResponseLookup methods */
void   response_lookup__init
                     (ResponseLookup         *message);
size_t response_lookup__get_packed_size
                     (const ResponseLookup   *message);
size_t response_lookup__pack
                     (const ResponseLookup   *message,
                      uint8_t             *out);
size_t response_lookup__pack_to_buffer
                     (const ResponseLookup   *message,
                      ProtobufCBuffer     *buffer);
ResponseLookup *
       response_lookup__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   response_lookup__free_unpacked
                     (ResponseLookup *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Field_Closure)
                 (const Field *message,
                  void *closure_data);
typedef void (*Document_Closure)
                 (const Document *message,
                  void *closure_data);
typedef void (*RequestDocumentAdd_Closure)
                 (const RequestDocumentAdd *message,
                  void *closure_data);
typedef void (*RequestDocumentRemove_Closure)
                 (const RequestDocumentRemove *message,
                  void *closure_data);
typedef void (*RequestLookup_Closure)
                 (const RequestLookup *message,
                  void *closure_data);
typedef void (*ResponseOperate_Closure)
                 (const ResponseOperate *message,
                  void *closure_data);
typedef void (*ResponseLookup_Closure)
                 (const ResponseLookup *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    error_code__descriptor;
extern const ProtobufCMessageDescriptor field__descriptor;
extern const ProtobufCMessageDescriptor document__descriptor;
extern const ProtobufCMessageDescriptor request_document_add__descriptor;
extern const ProtobufCMessageDescriptor request_document_remove__descriptor;
extern const ProtobufCMessageDescriptor request_lookup__descriptor;
extern const ProtobufCMessageDescriptor response_operate__descriptor;
extern const ProtobufCMessageDescriptor response_lookup__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_protocol_2eproto__INCLUDED */
