/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protocol.pb-c.h"
void   field__init
                     (Field         *message)
{
  static const Field init_value = FIELD__INIT;
  *message = init_value;
}
size_t field__get_packed_size
                     (const Field *message)
{
  assert(message->base.descriptor == &field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t field__pack
                     (const Field *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t field__pack_to_buffer
                     (const Field *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Field *
       field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Field *)
     protobuf_c_message_unpack (&field__descriptor,
                                allocator, len, data);
}
void   field__free_unpacked
                     (Field *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   document__init
                     (Document         *message)
{
  static const Document init_value = DOCUMENT__INIT;
  *message = init_value;
}
size_t document__get_packed_size
                     (const Document *message)
{
  assert(message->base.descriptor == &document__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t document__pack
                     (const Document *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &document__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t document__pack_to_buffer
                     (const Document *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &document__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Document *
       document__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Document *)
     protobuf_c_message_unpack (&document__descriptor,
                                allocator, len, data);
}
void   document__free_unpacked
                     (Document *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &document__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request_document_add__init
                     (RequestDocumentAdd         *message)
{
  static const RequestDocumentAdd init_value = REQUEST_DOCUMENT_ADD__INIT;
  *message = init_value;
}
size_t request_document_add__get_packed_size
                     (const RequestDocumentAdd *message)
{
  assert(message->base.descriptor == &request_document_add__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request_document_add__pack
                     (const RequestDocumentAdd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request_document_add__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request_document_add__pack_to_buffer
                     (const RequestDocumentAdd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request_document_add__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RequestDocumentAdd *
       request_document_add__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RequestDocumentAdd *)
     protobuf_c_message_unpack (&request_document_add__descriptor,
                                allocator, len, data);
}
void   request_document_add__free_unpacked
                     (RequestDocumentAdd *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request_document_add__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request_document_remove__init
                     (RequestDocumentRemove         *message)
{
  static const RequestDocumentRemove init_value = REQUEST_DOCUMENT_REMOVE__INIT;
  *message = init_value;
}
size_t request_document_remove__get_packed_size
                     (const RequestDocumentRemove *message)
{
  assert(message->base.descriptor == &request_document_remove__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request_document_remove__pack
                     (const RequestDocumentRemove *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request_document_remove__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request_document_remove__pack_to_buffer
                     (const RequestDocumentRemove *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request_document_remove__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RequestDocumentRemove *
       request_document_remove__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RequestDocumentRemove *)
     protobuf_c_message_unpack (&request_document_remove__descriptor,
                                allocator, len, data);
}
void   request_document_remove__free_unpacked
                     (RequestDocumentRemove *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request_document_remove__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request_lookup__init
                     (RequestLookup         *message)
{
  static const RequestLookup init_value = REQUEST_LOOKUP__INIT;
  *message = init_value;
}
size_t request_lookup__get_packed_size
                     (const RequestLookup *message)
{
  assert(message->base.descriptor == &request_lookup__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request_lookup__pack
                     (const RequestLookup *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request_lookup__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request_lookup__pack_to_buffer
                     (const RequestLookup *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request_lookup__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RequestLookup *
       request_lookup__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RequestLookup *)
     protobuf_c_message_unpack (&request_lookup__descriptor,
                                allocator, len, data);
}
void   request_lookup__free_unpacked
                     (RequestLookup *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request_lookup__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response_operate__init
                     (ResponseOperate         *message)
{
  static const ResponseOperate init_value = RESPONSE_OPERATE__INIT;
  *message = init_value;
}
size_t response_operate__get_packed_size
                     (const ResponseOperate *message)
{
  assert(message->base.descriptor == &response_operate__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response_operate__pack
                     (const ResponseOperate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response_operate__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response_operate__pack_to_buffer
                     (const ResponseOperate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response_operate__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResponseOperate *
       response_operate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResponseOperate *)
     protobuf_c_message_unpack (&response_operate__descriptor,
                                allocator, len, data);
}
void   response_operate__free_unpacked
                     (ResponseOperate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response_operate__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response_lookup__init
                     (ResponseLookup         *message)
{
  static const ResponseLookup init_value = RESPONSE_LOOKUP__INIT;
  *message = init_value;
}
size_t response_lookup__get_packed_size
                     (const ResponseLookup *message)
{
  assert(message->base.descriptor == &response_lookup__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response_lookup__pack
                     (const ResponseLookup *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response_lookup__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response_lookup__pack_to_buffer
                     (const ResponseLookup *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response_lookup__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResponseLookup *
       response_lookup__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResponseLookup *)
     protobuf_c_message_unpack (&response_lookup__descriptor,
                                allocator, len, data);
}
void   response_lookup__free_unpacked
                     (ResponseLookup *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response_lookup__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor field__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Field, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "term",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Field, term),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "valueStr",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Field, valuestr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "valueInt32",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Field, valueint32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indexable",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Field, indexable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned field__field_indices_by_name[] = {
  4,   /* field[4] = indexable */
  1,   /* field[1] = term */
  0,   /* field[0] = type */
  3,   /* field[3] = valueInt32 */
  2,   /* field[2] = valueStr */
};
static const ProtobufCIntRange field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor field__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Field",
  "Field",
  "Field",
  "",
  sizeof(Field),
  5,
  field__field_descriptors,
  field__field_indices_by_name,
  1,  field__number_ranges,
  (ProtobufCMessageInit) field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor document__field_descriptors[2] =
{
  {
    "pk",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Document, pk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fields",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Document, n_fields),
    offsetof(Document, fields),
    &field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned document__field_indices_by_name[] = {
  1,   /* field[1] = fields */
  0,   /* field[0] = pk */
};
static const ProtobufCIntRange document__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor document__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Document",
  "Document",
  "Document",
  "",
  sizeof(Document),
  2,
  document__field_descriptors,
  document__field_indices_by_name,
  1,  document__number_ranges,
  (ProtobufCMessageInit) document__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request_document_add__field_descriptors[1] =
{
  {
    "documents",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RequestDocumentAdd, n_documents),
    offsetof(RequestDocumentAdd, documents),
    &document__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request_document_add__field_indices_by_name[] = {
  0,   /* field[0] = documents */
};
static const ProtobufCIntRange request_document_add__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor request_document_add__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RequestDocumentAdd",
  "RequestDocumentAdd",
  "RequestDocumentAdd",
  "",
  sizeof(RequestDocumentAdd),
  1,
  request_document_add__field_descriptors,
  request_document_add__field_indices_by_name,
  1,  request_document_add__number_ranges,
  (ProtobufCMessageInit) request_document_add__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request_document_remove__field_descriptors[1] =
{
  {
    "pks",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(RequestDocumentRemove, n_pks),
    offsetof(RequestDocumentRemove, pks),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request_document_remove__field_indices_by_name[] = {
  0,   /* field[0] = pks */
};
static const ProtobufCIntRange request_document_remove__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor request_document_remove__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RequestDocumentRemove",
  "RequestDocumentRemove",
  "RequestDocumentRemove",
  "",
  sizeof(RequestDocumentRemove),
  1,
  request_document_remove__field_descriptors,
  request_document_remove__field_indices_by_name,
  1,  request_document_remove__number_ranges,
  (ProtobufCMessageInit) request_document_remove__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request_lookup__field_descriptors[2] =
{
  {
    "terms",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(RequestLookup, n_terms),
    offsetof(RequestLookup, terms),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "limit",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RequestLookup, limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request_lookup__field_indices_by_name[] = {
  1,   /* field[1] = limit */
  0,   /* field[0] = terms */
};
static const ProtobufCIntRange request_lookup__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor request_lookup__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RequestLookup",
  "RequestLookup",
  "RequestLookup",
  "",
  sizeof(RequestLookup),
  2,
  request_lookup__field_descriptors,
  request_lookup__field_indices_by_name,
  1,  request_lookup__number_ranges,
  (ProtobufCMessageInit) request_lookup__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response_operate__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ResponseOperate, code),
    &error_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ResponseOperate, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response_operate__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = msg */
};
static const ProtobufCIntRange response_operate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response_operate__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ResponseOperate",
  "ResponseOperate",
  "ResponseOperate",
  "",
  sizeof(ResponseOperate),
  2,
  response_operate__field_descriptors,
  response_operate__field_indices_by_name,
  1,  response_operate__number_ranges,
  (ProtobufCMessageInit) response_operate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response_lookup__field_descriptors[4] =
{
  {
    "documents",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ResponseLookup, n_documents),
    offsetof(ResponseLookup, documents),
    &document__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ResponseLookup, code),
    &error_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ResponseLookup, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ResponseLookup, total),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response_lookup__field_indices_by_name[] = {
  1,   /* field[1] = code */
  0,   /* field[0] = documents */
  2,   /* field[2] = msg */
  3,   /* field[3] = total */
};
static const ProtobufCIntRange response_lookup__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor response_lookup__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ResponseLookup",
  "ResponseLookup",
  "ResponseLookup",
  "",
  sizeof(ResponseLookup),
  4,
  response_lookup__field_descriptors,
  response_lookup__field_indices_by_name,
  1,  response_lookup__number_ranges,
  (ProtobufCMessageInit) response_lookup__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue error_code__enum_values_by_number[3] =
{
  { "ERROR_CODE_QUEUE_FULL", "ERROR_CODE__ERROR_CODE_QUEUE_FULL", -2 },
  { "ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE__ERROR_CODE_INVALID_ARGUMENT", -1 },
  { "ERROR_CODE_SUCCESS", "ERROR_CODE__ERROR_CODE_SUCCESS", 0 },
};
static const ProtobufCIntRange error_code__value_ranges[] = {
{-2, 0},{0, 3}
};
static const ProtobufCEnumValueIndex error_code__enum_values_by_name[3] =
{
  { "ERROR_CODE_INVALID_ARGUMENT", 1 },
  { "ERROR_CODE_QUEUE_FULL", 0 },
  { "ERROR_CODE_SUCCESS", 2 },
};
const ProtobufCEnumDescriptor error_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ErrorCode",
  "ErrorCode",
  "ErrorCode",
  "",
  3,
  error_code__enum_values_by_number,
  3,
  error_code__enum_values_by_name,
  1,
  error_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
